import tensorflow as tf
import numpy as np
from utils import extract_time, rnn_cell, random_generator, batch_generator

# Disable eager execution for compatibility with 1.x style code
tf.compat.v1.disable_eager_execution()

def timegan(ori_data, parameters):
    """TimeGAN function.
    
    Use original data as training set to generate synthetic data (time-series)
    
    Args:
        - ori_data: original time-series data
        - parameters: TimeGAN network parameters
        
    Returns:
        - generated_data: generated time-series data
    """
    
    # Initialization on the Graph
    tf.compat.v1.reset_default_graph()

    # Basic Parameters
    no, seq_len, dim = np.asarray(ori_data).shape

    # Maximum sequence length and each sequence length
    ori_time, max_seq_len = extract_time(ori_data)

    def MinMaxScaler(data):
        """Min-Max Normalizer.
        
        Args:
            - data: raw data
            
        Returns:
            - norm_data: normalized data
            - min_val: minimum values (for renormalization)
            - max_val: maximum values (for renormalization)
        """
        min_val = np.min(np.min(data, axis=0), axis=0)
        data = data - min_val

        max_val = np.max(np.max(data, axis=0), axis=0)
        norm_data = data / (max_val + 1e-7)

        return norm_data, min_val, max_val

    # Normalize the data
    ori_data, min_val, max_val = MinMaxScaler(ori_data)

    # Network Parameters
    hidden_dim = parameters['hidden_dim']
    num_layers = parameters['num_layer']
    iterations = parameters['iterations']
    batch_size = parameters['batch_size']
    module_name = parameters['module']
    z_dim = dim
    gamma = 1
    
    # Use tf.compat.v1.placeholder for compatibility with TF 1.x behavior
    X = tf.compat.v1.placeholder(tf.float32, [None, max_seq_len, dim], name="myinput_x")
    Z = tf.compat.v1.placeholder(tf.float32, [None, max_seq_len, z_dim], name="myinput_z")
    T = tf.compat.v1.placeholder(tf.int32, [None], name="myinput_t")

    def embedder(X, T):
        """Embedding network between original feature space to latent space.
        
        Args:
            - X: input time-series features
            - T: input time information
            
        Returns:
            - H: embeddings
        """
        with tf.compat.v1.variable_scope("embedder", reuse=tf.compat.v1.AUTO_REUSE):
            e_cells = [rnn_cell(module_name, hidden_dim) for _ in range(num_layers)]
            e_rnn = tf.keras.layers.RNN(e_cells, return_sequences=True)
            e_outputs = e_rnn(X)
            H = tf.keras.layers.Dense(hidden_dim, activation=tf.nn.sigmoid)(e_outputs)
        return H

    def recovery(H, T):
        """Recovery network from latent space to original space.
        
        Args:
            - H: latent representation
            - T: input time information
            
        Returns:
            - X_tilde: recovered data
        """
        with tf.compat.v1.variable_scope("recovery", reuse=tf.compat.v1.AUTO_REUSE):
            r_cells = [rnn_cell(module_name, hidden_dim) for _ in range(num_layers)]
            r_rnn = tf.keras.layers.RNN(r_cells, return_sequences=True)
            r_outputs = r_rnn(H)
            X_tilde = tf.keras.layers.Dense(dim, activation=tf.nn.sigmoid)(r_outputs)
        return X_tilde

    def generator(Z, T):
        """Generator function: Generate time-series data in latent space.
        
        Args:
            - Z: random variables
            - T: input time information
            
        Returns:
            - E: generated embedding
        """
        with tf.compat.v1.variable_scope("generator", reuse=tf.compat.v1.AUTO_REUSE):
            e_cells = [rnn_cell(module_name, hidden_dim) for _ in range(num_layers)]
            e_rnn = tf.keras.layers.RNN(e_cells, return_sequences=True)
            e_outputs = e_rnn(Z)
            E = tf.keras.layers.Dense(hidden_dim, activation=tf.nn.sigmoid)(e_outputs)
        return E

    def supervisor(H, T):
        """Generate next sequence using the previous sequence.
        
        Args:
            - H: latent representation
            - T: input time information
            
        Returns:
            - S: generated sequence based on the latent representations generated by the generator
        """
        with tf.compat.v1.variable_scope("supervisor", reuse=tf.compat.v1.AUTO_REUSE):
            e_cells = [rnn_cell(module_name, hidden_dim) for _ in range(num_layers - 1)]
            e_rnn = tf.keras.layers.RNN(e_cells, return_sequences=True)
            e_outputs = e_rnn(H)
            S = tf.keras.layers.Dense(hidden_dim, activation=tf.nn.sigmoid)(e_outputs)
        return S

    def discriminator(H, T):
        """Discriminate the original and synthetic time-series data.
        
        Args:
            - H: latent representation
            - T: input time information
            
        Returns:
            - Y_hat: classification results between original and synthetic time-series
        """
        with tf.compat.v1.variable_scope("discriminator", reuse=tf.compat.v1.AUTO_REUSE):
            d_cells = [rnn_cell(module_name, hidden_dim) for _ in range(num_layers)]
            d_rnn = tf.keras.layers.RNN(d_cells, return_sequences=True)
            d_outputs = d_rnn(H)
            Y_hat = tf.keras.layers.Dense(1)(d_outputs)
        return Y_hat

    # Embedder & Recovery
    H = embedder(X, T)
    X_tilde = recovery(H, T)

    # Generator
    E_hat = generator(Z, T)
    H_hat = supervisor(E_hat, T)
    H_hat_supervise = supervisor(H, T)

    # Synthetic data
    X_hat = recovery(H_hat, T)

    # Discriminator
    Y_fake = discriminator(H_hat, T)
    Y_real = discriminator(H, T)
    Y_fake_e = discriminator(E_hat, T)

    # Variables
    e_vars = [v for v in tf.compat.v1.trainable_variables() if v.name.startswith('embedder')]
    r_vars = [v for v in tf.compat.v1.trainable_variables() if v.name.startswith('recovery')]
    g_vars = [v for v in tf.compat.v1.trainable_variables() if v.name.startswith('generator')]
    s_vars = [v for v in tf.compat.v1.trainable_variables() if v.name.startswith('supervisor')]
    d_vars = [v for v in tf.compat.v1.trainable_variables() if v.name.startswith('discriminator')]

    # Loss Functions
    D_loss_real = tf.compat.v1.losses.sigmoid_cross_entropy(tf.ones_like(Y_real), Y_real)
    D_loss_fake = tf.compat.v1.losses.sigmoid_cross_entropy(tf.zeros_like(Y_fake), Y_fake)
    D_loss_fake_e = tf.compat.v1.losses.sigmoid_cross_entropy(tf.zeros_like(Y_fake_e), Y_fake_e)
    D_loss = D_loss_real + D_loss_fake + gamma * D_loss_fake_e

    G_loss_U = tf.compat.v1.losses.sigmoid_cross_entropy(tf.ones_like(Y_fake), Y_fake)
    G_loss_U_e = tf.compat.v1.losses.sigmoid_cross_entropy(tf.ones_like(Y_fake_e), Y_fake_e)

    G_loss_S = tf.compat.v1.losses.mean_squared_error(H[:, 1:, :], H_hat_supervise[:, :-1, :])

    G_loss_V1 = tf.reduce_mean(tf.abs(tf.sqrt(tf.nn.moments(X_hat, [0])[1] + 1e-6) - tf.sqrt(tf.nn.moments(X, [0])[1] + 1e-6)))
    G_loss_V2 = tf.reduce_mean(tf.abs((tf.nn.moments(X_hat, [0])[0]) - (tf.nn.moments(X, [0])[0])))

    G_loss_V = G_loss_V1 + G_loss_V2

    G_loss = G_loss_U + gamma * G_loss_U_e + 100 * tf.sqrt(G_loss_S) + 100 * G_loss_V

    E_loss_T0 = tf.compat.v1.losses.mean_squared_error(X, X_tilde)
    E_loss0 = 10 * tf.compat.v1.sqrt(E_loss_T0)
    E_loss = E_loss0 + 0.1 * G_loss_S

    # Optimizers
    E0_solver = tf.compat.v1.train.AdamOptimizer().minimize(E_loss0, var_list=e_vars + r_vars)
    E_solver = tf.compat.v1.train.AdamOptimizer().minimize(E_loss, var_list=e_vars + r_vars)
    D_solver = tf.compat.v1.train.AdamOptimizer().minimize(D_loss, var_list=d_vars)
    G_solver = tf.compat.v1.train.AdamOptimizer().minimize(G_loss, var_list=g_vars + s_vars)
    GS_solver = tf.compat.v1.train.AdamOptimizer().minimize(G_loss_S, var_list=g_vars + s_vars)

    # Session setup
    sess = tf.compat.v1.Session()
    sess.run(tf.compat.v1.global_variables_initializer())

    # Embedding network training
    print('Start Embedding Network Training')

    for itt in range(iterations):
        # Set mini-batch
        X_mb, T_mb = batch_generator(ori_data, ori_time, batch_size)
        # Train embedder
        _, step_e_loss = sess.run([E0_solver, E_loss_T0], feed_dict={X: X_mb, T: T_mb})
        if itt % 1000 == 0:
            print('step: ' + str(itt) + '/' + str(iterations) + ', e_loss: ' + str(np.round(np.sqrt(step_e_loss), 4)))

    print('Finish Embedding Network Training')

    # Further training steps and synthetic data generation can be handled similarly

    return generated_data
